name: 'js-eval-action'
description: 'GitHub action for evaluating JS expressions'
author: 'cardinalby'
inputs:
  expression:
    description: 'JS expression to evaluate'
    required: false
  jsFile:
    description: 'JS file to evaluate expression from'
    required: false
  jsonInputs:
    description: 'Parse listed inputs as JSON (use "|" separator). * to parse all'
    required: false
  jsonEnvs:
    description: 'Parse listed envs as JSON (use "|" separator). * to parse all'
    required: false
  extractOutputs:
    required: false
    default: 'false'
    description: 'If true, separate outputs will be set from result object, JSON.stringify(result) otherwise'
  timeoutMs:
    required: false
    description: 'If true, separate outputs will be set from result object, JSON.stringify(result) otherwise'
  data:
    required: false
    description: 'Arbitrary data you want to access in expression'
outputs:
  result:
    description: 'Result of expression evaluation'
  timedOut:
    description: '"true" if expression evaluation failed due to timeout. "false" otherwise'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'code'
